### PR TITLE
Issue #6: Fix NPE on toggleAppender

### LINKED ISSUE #521: Cannot pass BlockPhysicsEvent
[15:51:00] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to CastleGates v2.0.0
java.lang.NullPointerException: Cannot invoke "com.untamedears.jukealert.model.appender.LeverToggleAppender.shouldToggle()" because "toggleAppender" is null
	at com.aleksey.castlegates.plugins.jukealert.JukeAlertManager.hasJukeAlertAccess(JukeAlertManager.java:30) ~[castlegates-paper-2.0.1.jar:?]
	at com.aleksey.castlegates.plugins.citadel.CitadelManager.getCitadel(CitadelManager.java:81) ~[castlegates-paper-2.0.1.jar:?]
	at com.aleksey.castlegates.engine.bridge.BridgeManager.getCitadel(BridgeManager.java:723) ~[castlegates-paper-2.0.1.jar:?]
	at com.aleksey.castlegates.engine.bridge.BridgeManager.processGearblock(BridgeManager.java:232) ~[castlegates-paper-2.0.1.jar:?]
	at com.aleksey.castlegates.engine.bridge.BridgeEventHandler.processBlock(BridgeEventHandler.java:409) ~[castlegates-paper-2.0.1.jar:?]
	at com.aleksey.castlegates.engine.bridge.BridgeEventHandler.handleBlockPhysics(BridgeEventHandler.java:116) ~[castlegates-paper-2.0.1.jar:?]
	at com.aleksey.castlegates.engine.CastleGatesManager.handleBlockPhysics(CastleGatesManager.java:119) ~[castlegates-paper-2.0.1.jar:?]
	at com.aleksey.castlegates.listener.BlockListener.onBlockPhysics(BlockListener.java:32) ~[castlegates-paper-2.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor625.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-387]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.Level.neighborChanged(Level.java:763) ~[?:?]
	at net.minecraft.world.level.block.ObserverBlock.updateNeighborsInFront(ObserverBlock.java:84) ~[?:?]
	at net.minecraft.world.level.block.ObserverBlock.tick(ObserverBlock.java:61) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1015) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1082) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:616) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

### PR DESCRIPTION
**Pull request by Diet-Cola**

### CODE REVIEW

File: paper/src/main/java/com/aleksey/castlegates/plugins/jukealert/JukeAlertManager.java [hunk 1]
```diff
@@ -27,6 +27,9 @@ public boolean hasJukeAlertAccess(Location location, String groupName) {
 						)
 				{
 					LeverToggleAppender toggleAppender = snitch.getAppender(LeverToggleAppender.class);
+					if (toggleAppender == null) {
+						return false;
```
Comment (Aleksey-Terzi) [inline paper/src/main/java/com/aleksey/castlegates/plugins/jukealert/JukeAlertManager.java]: I propose to use here `continue`
If there is more than one neighboring snitch then any of them should have possibility to trigger CG.
For example, **snitch 1** may not have LeverToggleAppender but **snitch 2** can have it and therefore we should trigger CG

**Review by Aleksey-Terzi — APPROVED** [review]
Looks good, thanks
